apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  externalTrafficPolicy: "Local"
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
